<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/crypto.proto

namespace libp2p\Protobuf\Crypto;

use UnexpectedValueException;

/**
 * Protobuf type <code>KeyType</code>
 */
class KeyType
{
    /**
     * Generated from protobuf enum <code>RSA = 0;</code>
     */
    const RSA = 0;
    /**
     * Generated from protobuf enum <code>Ed25519 = 1;</code>
     */
    const Ed25519 = 1;
    /**
     * Generated from protobuf enum <code>Secp256k1 = 2;</code>
     */
    const Secp256k1 = 2;

    private static $valueToName = [
        self::RSA => 'RSA',
        self::Ed25519 => 'Ed25519',
        self::Secp256k1 => 'Secp256k1',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

