<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/crypto.proto

namespace libp2p\Protobuf\Crypto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PrivateKey</code>
 */
class PrivateKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.KeyType Type = 1;</code>
     */
    protected $Type = 0;
    /**
     * Generated from protobuf field <code>bytes Data = 2;</code>
     */
    protected $Data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Type
     *     @type string $Data
     * }
     */
    public function __construct($data = NULL) {
        \libp2p\Protobuf\Meta\Crypto\Crypto::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.KeyType Type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>.KeyType Type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \libp2p\Protobuf\Crypto\KeyType::class);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>bytes Data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->Data = $var;

        return $this;
    }

}

