<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/peer.proto

namespace libp2p\Protobuf\Peer\Record;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Record.AddressInfo</code>
 */
class AddressInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes multiaddr = 1;</code>
     */
    protected $multiaddr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $multiaddr
     * }
     */
    public function __construct($data = NULL) {
        \libp2p\Protobuf\Meta\Peer\Peer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes multiaddr = 1;</code>
     * @return string
     */
    public function getMultiaddr()
    {
        return $this->multiaddr;
    }

    /**
     * Generated from protobuf field <code>bytes multiaddr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMultiaddr($var)
    {
        GPBUtil::checkString($var, False);
        $this->multiaddr = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AddressInfo::class, \libp2p\Protobuf\Peer\Record_AddressInfo::class);

