<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/noise.proto

namespace libp2p\Protobuf\Noise;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HandshakePayload</code>
 */
class HandshakePayload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes identity_key = 1;</code>
     */
    protected $identity_key = '';
    /**
     * Generated from protobuf field <code>bytes identity_sig = 2;</code>
     */
    protected $identity_sig = '';
    /**
     * Generated from protobuf field <code>optional bytes data = 3;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identity_key
     *     @type string $identity_sig
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \libp2p\Protobuf\Meta\Noise\Noise::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes identity_key = 1;</code>
     * @return string
     */
    public function getIdentityKey()
    {
        return $this->identity_key;
    }

    /**
     * Generated from protobuf field <code>bytes identity_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->identity_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes identity_sig = 2;</code>
     * @return string
     */
    public function getIdentitySig()
    {
        return $this->identity_sig;
    }

    /**
     * Generated from protobuf field <code>bytes identity_sig = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentitySig($var)
    {
        GPBUtil::checkString($var, False);
        $this->identity_sig = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return isset($this->data) ? $this->data : '';
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>optional bytes data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

