<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/peer.proto

namespace libp2p\Protobuf\Peer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ID</code>
 */
class ID extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>optional bytes pubKey = 2;</code>
     */
    protected $pubKey = null;
    /**
     * Generated from protobuf field <code>optional bytes privKey = 3;</code>
     */
    protected $privKey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $pubKey
     *     @type string $privKey
     * }
     */
    public function __construct($data = NULL) {
        \libp2p\Protobuf\Meta\Peer\Peer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes pubKey = 2;</code>
     * @return string
     */
    public function getPubKey()
    {
        return isset($this->pubKey) ? $this->pubKey : '';
    }

    public function hasPubKey()
    {
        return isset($this->pubKey);
    }

    public function clearPubKey()
    {
        unset($this->pubKey);
    }

    /**
     * Generated from protobuf field <code>optional bytes pubKey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPubKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes privKey = 3;</code>
     * @return string
     */
    public function getPrivKey()
    {
        return isset($this->privKey) ? $this->privKey : '';
    }

    public function hasPrivKey()
    {
        return isset($this->privKey);
    }

    public function clearPrivKey()
    {
        unset($this->privKey);
    }

    /**
     * Generated from protobuf field <code>optional bytes privKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->privKey = $var;

        return $this;
    }

}

