<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/peer.proto

namespace libp2p\Protobuf\Peer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes peer_id = 1;</code>
     */
    protected $peer_id = '';
    /**
     * Generated from protobuf field <code>uint64 seq = 2;</code>
     */
    protected $seq = 0;
    /**
     * Generated from protobuf field <code>repeated .Record.AddressInfo addresses = 3;</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $peer_id
     *     @type int|string $seq
     *     @type \libp2p\Protobuf\Peer\Record\AddressInfo[]|\Google\Protobuf\Internal\RepeatedField $addresses
     * }
     */
    public function __construct($data = NULL) {
        \libp2p\Protobuf\Meta\Peer\Peer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes peer_id = 1;</code>
     * @return string
     */
    public function getPeerId()
    {
        return $this->peer_id;
    }

    /**
     * Generated from protobuf field <code>bytes peer_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerId($var)
    {
        GPBUtil::checkString($var, False);
        $this->peer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 seq = 2;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>uint64 seq = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint64($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Record.AddressInfo addresses = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .Record.AddressInfo addresses = 3;</code>
     * @param \libp2p\Protobuf\Peer\Record\AddressInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \libp2p\Protobuf\Peer\Record\AddressInfo::class);
        $this->addresses = $arr;

        return $this;
    }

}

