<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/peer.proto

namespace libp2p\Protobuf\Peer;

if (false) {
    /**
     * This class is deprecated. Use libp2p\Protobuf\Peer\Record\AddressInfo instead.
     * @deprecated
     */
    class Record_AddressInfo {}
}
class_exists(Record\AddressInfo::class);
@trigger_error('libp2p\Protobuf\Peer\Record_AddressInfo is deprecated and will be removed in the next major release. Use libp2p\Protobuf\Peer\Record\AddressInfo instead', E_USER_DEPRECATED);

